const COLORS=['#00F0FF','#FF007F','#00FF66','#FFA53C','#B15CFF','#39C7FF'];
const SOLUTION='#FFE600', MIN_COLOR='#00FF66', MAX_COLOR='#FFA53C';
const DOMAIN_MIN=-30, DOMAIN_MAX=30, XMIN=-10, XMAX=10, YMIN=-10, YMAX=10, SNAP_TOLERANCE=.01;
const state={ineq:[],steps:[],stepIdx:-1,showVertices:false,showObjective:false,objA:1,objB:1,objF:0,snapVertex:null,view:{x0:XMIN,x1:XMAX,y0:YMIN,y1:YMAX},auto:null,activeField:'a'};
const $=id=>document.getElementById(id), fmtN=v=>{v=Math.round(v*1e4)/1e4; return Number.isInteger(v)?String(v):String(v)};
function frac(v){let r=Math.round(v*1e6)/1e6;if(Math.abs(r-Math.round(r))<1e-6)return String(Math.round(r));let best=[1,0],bestErr=1e9;for(let d=1;d<=1000;d++){let n=Math.round(r*d),e=Math.abs(r-n/d);if(e<bestErr){best=[n,d];bestErr=e}}if(best[1]===1)return String(best[0]);return `${best[0]}/${best[1]}`}
function parseCoef(s){s=String(s).trim();if(s==='')throw Error('Thiếu hệ số.');if(s.includes('/')){let [a,b]=s.split('/');if(b===''||Number(b)===0)throw Error('Mẫu số không hợp lệ.');return (a===''?1:Number(a))/Number(b)}let v=Number(s);if(!Number.isFinite(v))throw Error(`Hệ số không hợp lệ: ${s}`);return v}
function parseExpr(expr){expr=expr.replace(/\s+/g,'');if(!expr)return{x:0,y:0,c:0};if(!/^[+-]/.test(expr))expr='+'+expr;let terms=expr.match(/[+-][^+-]+/g);if(!terms||terms.join('')!==expr)throw Error(`Biểu thức không hợp lệ: ${expr}`);let out={x:0,y:0,c:0};for(const term of terms){let sign=term[0]==='-'?-1:1,body=term.slice(1);if(!body)throw Error('Số hạng rỗng.');let m=body.match(/[xy]/);let variable=m?m[0]:'';let coefStr=m?body.slice(0,m.index)+body.slice(m.index+1):body;if(variable && (coefStr==='' ))coefStr='1';if(!/^\d*\.?\d*(?:\/\d*\.?\d*)?$/.test(coefStr))throw Error(`Không thể phân tích số hạng: ${term}`);let coef=coefStr===''?1:parseCoef(coefStr);if(variable==='x')out.x+=sign*coef;else if(variable==='y')out.y+=sign*coef;else out.c+=sign*coef}return out}
function parseIneq(raw){let s=raw.trim();if(!s)throw Error('Vui lòng nhập bất phương trình.');let m=s.match(/(<=|>=|<|>|=)/);if(!m)throw Error('Thiếu dấu so sánh.');let left=parseExpr(s.slice(0,m.index)),right=parseExpr(s.slice(m.index+m[0].length));let a=left.x-right.x,b=left.y-right.y,c=right.c-left.c;if(Math.abs(a)<1e-9&&Math.abs(b)<1e-9)throw Error('Bất phương trình phải chứa x hoặc y.');return{a,b,c,op:m[0],raw:s,visible:true,color:COLORS[state.ineq.length%COLORS.length]}}
function opDisplay(op){return {'<=':'≤','>=':'≥','<':'<','>':'>','=':'='}[op]}
function formatLinear(a,b,c,op='='){function term(q,v){if(Math.abs(q)<1e-9)return null;let r=Math.round(q*1e4)/1e4;if(r===1)return v;if(r===-1)return '-'+v;return `${r}${v}`}let tx=term(a,'x'),ty=term(b,'y'),p=[];if(tx)p.push(tx);if(ty)p.push(p.length?(ty.startsWith('-')?'- '+ty.slice(1):'+ '+ty):ty);if(!p.length)p.push('0');return `${p.join(' ')} ${opDisplay(op)||op} ${fmtN(c)}`}
function satisfied(q,x,y){let v=q.a*x+q.b*y,c=q.c;switch(q.op){case '<=':return v<=c+1e-9;case '>=':return v>=c-1e-9;case '<':return v<c-1e-9;case '>':return v>c+1e-9;default:return Math.abs(v-c)<1e-6}}
function testPoint(q){for(const p of [[0,0],[1,0],[0,1],[2,3],[1,1],[-1,2]])if(Math.abs(q.a*p[0]+q.b*p[1]-q.c)>1e-6)return p;return[5,7]}
function clip(poly,a,b,c,keep){if(!poly.length)return[];const inside=p=>keep==='le'?a*p[0]+b*p[1]<=c+1e-9:a*p[0]+b*p[1]>=c-1e-9;const inter=(p1,p2)=>{let v1=a*p1[0]+b*p1[1]-c,v2=a*p2[0]+b*p2[1]-c,t=v1/(v1-v2);return[p1[0]+t*(p2[0]-p1[0]),p1[1]+t*(p2[1]-p1[1])]};let out=[];for(let i=0;i<poly.length;i++){let cur=poly[i],prev=poly[(i+poly.length-1)%poly.length],ci=inside(cur),pi=inside(prev);if(ci){if(!pi)out.push(inter(prev,cur));out.push(cur)}else if(pi)out.push(inter(prev,cur))}return out}
function halfplane(q){let rect=[[DOMAIN_MIN,DOMAIN_MIN],[DOMAIN_MAX,DOMAIN_MIN],[DOMAIN_MAX,DOMAIN_MAX],[DOMAIN_MIN,DOMAIN_MAX]];if(q.op==='=')return linePolygon(q);let keep=['<=','<'].includes(q.op)?'le':'ge';return clip(rect,q.a,q.b,q.c,keep)}
function linePolygon(q){let p=halfplane({...q,op:'<='});return p}
function vertices(){let active=state.ineq.filter(q=>q.visible),pts=[];for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){let q1=active[i],q2=active[j],det=q1.a*q2.b-q2.a*q1.b;if(Math.abs(det)<1e-9)continue;let x=(q1.c*q2.b-q2.c*q1.b)/det,y=(q1.a*q2.c-q2.a*q1.c)/det;if(active.every(q=>satisfied(q,x,y)))pts.push([x,y])}let u=[];for(const p of pts)if(!u.some(v=>Math.hypot(p[0]-v[0],p[1]-v[1])<1e-6))u.push(p);if(u.length<3)return u;let cx=u.reduce((s,p)=>s+p[0],0)/u.length,cy=u.reduce((s,p)=>s+p[1],0)/u.length;return u.sort((p,q)=>Math.atan2(p[1]-cy,p[0]-cx)-Math.atan2(q[1]-cy,q[0]-cx))}
function objectiveRows(){let vs=vertices();let rows=vs.map(p=>({x:p[0],y:p[1],F:state.objA*p[0]+state.objB*p[1]}));if(!rows.length)return{rows,min:null,max:null};return{rows,min:rows.reduce((a,b)=>b.F<a.F?b:a),max:rows.reduce((a,b)=>b.F>a.F?b:a)}}
function explanation(step){if(!step)return'Nhập hệ bất phương trình rồi bấm “⚙ Giải hệ”.';let total=state.steps.length,head=`BƯỚC ${step.no}/${total}\n──────────────────────────\n`;if(step.type==='line'){let q=state.ineq[step.idx],strict=['<','>'].includes(q.op);return head+`Vẽ đường thẳng biên d${step.idx+1} của bất phương trình (${q.raw}):\n\n    d${step.idx+1}:  ${formatLinear(q.a,q.b,q.c)}\n\nĐường được vẽ bằng ${strict?'nét đứt':'nét liền'}, màu neon đại diện cho BPT ${step.idx+1}.`}if(step.type==='test'){let q=state.ineq[step.idx],p=testPoint(q),val=q.a*p[0]+q.b*p[1],ok=satisfied(q,...p);return head+`Chọn điểm thử M(${fmtN(p[0])}; ${fmtN(p[1])}).\n\nThay vào vế trái:\n    ${fmtN(q.a)}×${fmtN(p[0])} + ${fmtN(q.b)}×${fmtN(p[1])} = ${fmtN(val)}\n\nSo sánh: ${fmtN(val)} ${opDisplay(q.op)} ${fmtN(q.c)}  →  ${ok?'ĐÚNG ✓':'SAI ✗'}\n\n⇒ Miền nghiệm của BPT ${step.idx+1} là nửa mặt phẳng ${ok?'CHỨA điểm thử':'KHÔNG chứa điểm thử'}.`}if(step.type==='conclusion')return head+'KẾT LUẬN\n\nMiền nghiệm của cả hệ là phần GIAO NHAU của tất cả các miền nghiệm riêng lẻ. Vùng này được làm sáng bằng màu VÀNG NEON trên đồ thị. Bấm “📐 Hiện đỉnh” để xem tọa độ các đỉnh.';if(step.type==='optimize'){let{rows,min,max}=objectiveRows();let obj=`${frac(state.objA)}x + ${frac(state.objB)}y`;if(rows.length<3)return head+`TỐI ƯU HÀM MỤC TIÊU F = ${obj}\n\nMiền nghiệm không tạo thành một đa giác kín có ít nhất 3 đỉnh, nên không thể chốt min/max hữu hạn bằng cách kiểm tra các đỉnh.`;let s=rows.map(r=>`(${frac(r.x)}; ${frac(r.y)})    ${fmtN(r.F)}${r===min?'  ← min':''}${r===max?'  ← max':''}`).join('\n');return head+`TỐI ƯU HÀM MỤC TIÊU F = ${obj}\n\nGiá trị F được kiểm tra tại từng đỉnh:\n\nĐỉnh (x;y)          F\n------------------------------\n${s}\n\n• F nhỏ nhất = ${fmtN(min.F)} tại (${frac(min.x)}; ${frac(min.y)})\n• F lớn nhất = ${fmtN(max.F)} tại (${frac(max.x)}; ${frac(max.y)})\n\n⇒ Kết luận: min F = ${fmtN(min.F)} tại (${frac(min.x)}; ${frac(min.y)}); max F = ${fmtN(max.F)} tại (${frac(max.x)}; ${frac(max.y)}).`}}
function buildSteps(){state.steps=[];state.ineq.forEach((q,i)=>{state.steps.push({type:'line',idx:i,no:state.steps.length+1});state.steps.push({type:'test',idx:i,no:state.steps.length+1})});if(state.ineq.length){state.steps.push({type:'conclusion',no:state.steps.length+1});if(state.showObjective)state.steps.push({type:'optimize',no:state.steps.length+1})}}
function setStatus(msg,error=false){$('status').textContent=msg;$('status').className='status'+(error?' error':'')}
function addIneqText(raw){try{state.ineq.push(parseIneq(raw));refreshList();invalidate();setStatus(`Đã thêm: ${raw}`)}catch(e){setStatus('⚠ '+e.message,true)}}
function invalidate(){buildSteps();state.stepIdx=-1;state.snapVertex=null;render()}
function refreshList(){let box=$('ineqList');box.innerHTML='';state.ineq.forEach((q,i)=>{let row=document.createElement('div');row.className='ineq-row';row.innerHTML=`<input type="checkbox" ${q.visible?'checked':''} title="Hiện/ẩn"><span class="swatch" style="background:${q.color}"></span><span class="ineq-text">${q.raw}</span><button class="delete-btn">✕</button>`;row.querySelector('input').onchange=e=>{q.visible=e.target.checked;invalidate()};row.querySelector('.delete-btn').onclick=()=>{state.ineq.splice(i,1);state.ineq.forEach((x,j)=>x.color=COLORS[j%COLORS.length]);invalidate();refreshList()};box.appendChild(row)})}
function solve(){if(!state.ineq.length){setStatus('⚠ Hãy thêm ít nhất một bất phương trình.',true);return}buildSteps();state.stepIdx=0;render();setStatus(`Đã giải: ${state.steps.length} bước.`)}
function reset(){state.ineq=[];state.steps=[];state.stepIdx=-1;state.showVertices=false;state.showObjective=false;state.objA=1;state.objB=1;state.objF=0;state.snapVertex=null;state.view={x0:XMIN,x1:XMAX,y0:YMIN,y1:YMAX};$('coefA').value='1';$('coefB').value='0';$('coefC').value='0';$('objA').value='1';$('objB').value='1';$('objToggle').textContent='📈 Hiện đường mức F';$('objControls').classList.add('hidden');$('verticesBtn').textContent='📐 Hiện đỉnh';clearAuto();loadDefault();setStatus('Đã đặt lại hệ mẫu.')}
function loadDefault(){['2x + y <= 4','x - y <= 1','x >= 0','y >= 0'].forEach(addIneqText)}
function clearAuto(){if(state.auto)clearInterval(state.auto);state.auto=null;$('autoBtn').textContent='⏵ Auto Play (2.5s / bước)'}
function autoPlay(){if(!state.steps.length){setStatus('⚠ Hãy giải hệ trước khi dùng Auto Play.',true);return}if(state.auto){clearAuto();return}$('autoBtn').textContent='⏸ Dừng Auto Play';if(state.stepIdx>=state.steps.length-1){state.stepIdx=0;render()}state.auto=setInterval(()=>{if(state.stepIdx<state.steps.length-1){state.stepIdx++;render()}else clearAuto()},2500)}
function objectiveBounds(){let v=state.view,c=[[v.x0,v.y0],[v.x0,v.y1],[v.x1,v.y0],[v.x1,v.y1]].map(p=>state.objA*p[0]+state.objB*p[1]);return[Math.min(...c),Math.max(...c)]}
function setObjectiveCoeff(){let a=parseFloat($('objA').value),b=parseFloat($('objB').value);if(!Number.isFinite(a)||!Number.isFinite(b)||Math.abs(a)+Math.abs(b)<1e-9){setStatus('⚠ Hệ số a, b của F không được đồng thời bằng 0.',true);return}state.objA=a;state.objB=b;let [mn,mx]=objectiveBounds(),mid=(mn+mx)/2;state.objF=mid;$('objSlider').min=mn;$('objSlider').max=mx;$('objSlider').value=mid;updateObjLabel();render()}
function snapF(raw){let vs=vertices(),norm=Math.hypot(state.objA,state.objB),best=null;if(norm<1e-9)return[raw,null];for(const v of vs){let f=state.objA*v[0]+state.objB*v[1],d=Math.abs(f-raw)/norm;if(d<=SNAP_TOLERANCE&&(!best||d<best.d))best={f,v,d}}return best?[best.f,best.v]:[raw,null]}
function updateObjLabel(){$('objFLabel').textContent=`F = ${frac(state.objA)}x + ${frac(state.objB)}y = ${fmtN(state.objF)}`}
function toggleObjective(){state.showObjective=!state.showObjective;$('objToggle').textContent=state.showObjective?'📈 Ẩn đường mức F':'📈 Hiện đường mức F';$('objControls').classList.toggle('hidden',!state.showObjective);if(state.showObjective)setObjectiveCoeff();buildSteps();render()}
function svgEl(name,attrs={},parent){let e=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(parent)parent.appendChild(e);return e}
function scalePoint(x,y,W,H){let v=state.view;return[((x-v.x0)/(v.x1-v.x0))*W,(1-(y-v.y0)/(v.y1-v.y0))*H]}
function render(){let svg=$('graph');svg.innerHTML='';let W=900,H=700,v=state.view;const [sx,sy]=(p)=>scalePoint(p[0],p[1],W,H);let defs=svgEl('defs',{},svg);let glow=svgEl('filter',{id:'glow'},defs);svgEl('feGaussianBlur',{stdDeviation:'3',result:'b'},glow);let mer=svgEl('feMerge',{},glow);svgEl('feMergeNode',{in:'b'},mer);svgEl('feMergeNode',{in:'SourceGraphic'},mer);
 svgEl('rect',{x:0,y:0,width:W,height:H,fill:'#0D0D11'},svg);
 const gx0=Math.ceil(v.x0),gx1=Math.floor(v.x1),gy0=Math.ceil(v.y0),gy1=Math.floor(v.y1);for(let x=gx0;x<=gx1;x++){let p=sx([x,v.y0]),q=sx([x,v.y1]);svgEl('line',{x1:p[0],y1:p[1],x2:q[0],y2:q[1],stroke:'#2A2A38','stroke-width':.7},svg)}for(let y=gy0;y<=gy1;y++){let p=sx([v.x0,y]),q=sx([v.x1,y]);svgEl('line',{x1:p[0],y1:p[1],x2:q[0],y2:q[1],stroke:'#2A2A38','stroke-width':.7},svg)}
 let o=sx([0,0]);svgEl('line',{x1:0,y1:o[1],x2:W,y2:o[1],stroke:'#71718A','stroke-width':1.4},svg);svgEl('line',{x1:o[0],y1:0,x2:o[0],y2:H,stroke:'#71718A','stroke-width':1.4},svg);
 for(let x=gx0;x<=gx1;x++){if(x===0)continue;let p=sx([x,0]);text(svg,String(x),p[0]+3,p[1]-4,9,'#E2E8F0','middle')}for(let y=gy0;y<=gy1;y++){if(y===0)continue;let p=sx([0,y]);text(svg,String(y),p[0]+5,p[1]-3,9,'#E2E8F0','start')}
 const current=state.stepIdx>=0?state.steps[state.stepIdx]:null;let drawnCount=current?.type==='line'||current?.type==='test'?current.idx+1:state.ineq.length;for(let i=0;i<drawnCount;i++){let q=state.ineq[i];if(!q.visible)continue;let poly=halfplane(q),pts=poly.map(p=>sx(p));if(pts.length>=3){let path=pts.map((p,j)=>`${j?'L':'M'}${p[0]} ${p[1]}`).join(' ')+' Z';let opacity=state.stepIdx>=0?(.10):.08;svgEl('path',{d:path,fill:q.color,opacity,stroke:'none'},svg)}}
 if(current?.type==='test'){let q=state.ineq[current.idx],p=testPoint(q),pp=sx(p);svgEl('circle',{cx:pp[0],cy:pp[1],r:7,fill:'#fff',stroke:q.color,'stroke-width':3},svg);text(svg,`M(${fmtN(p[0])}; ${fmtN(p[1])})`,pp[0]+10,pp[1]-10,11,'#fff','start')}
 state.ineq.forEach((q,i)=>{if(!q.visible)return;let a=q.a,b=q.b,c=q.c,x0=v.x0,x1=v.x1,y0=v.y0,y1=v.y1;let pts=[];if(Math.abs(b)>1e-9)pts=[[x0,(c-a*x0)/b],[x1,(c-a*x1)/b]];else{let x=c/a;pts=[[x,y0],[x,y1]]}let P=pts.map(sx);svgEl('line',{x1:P[0][0],y1:P[0][1],x2:P[1][0],y2:P[1][1],stroke:q.color,'stroke-width':3,'stroke-dasharray':['<','>'].includes(q.op)?'7 6':'none'},svg)});
 let conc=current?.type==='conclusion'||current?.type==='optimize';if(conc){let vs=vertices();if(vs.length>=3){let pts=vs.map(sx),path=pts.map((p,j)=>`${j?'L':'M'}${p[0]} ${p[1]}`).join(' ')+' Z';svgEl('path',{d:path,fill:SOLUTION,opacity:.22,stroke:SOLUTION,'stroke-width':4,filter:'url(#glow)'},svg)}}
 if(state.showObjective){let a=state.objA,b=state.objB,F=state.objF;if(Math.abs(b)>1e-9){let pts=[[v.x0,(F-a*v.x0)/b],[v.x1,(F-a*v.x1)/b]].map(sx);svgEl('line',{x1:pts[0][0],y1:pts[0][1],x2:pts[1][0],y2:pts[1][1],stroke:'#FF3EC9','stroke-width':3,'stroke-dasharray':'5 5',filter:'url(#glow)'},svg)}else{let x=F/a,p=sx([x,v.y0]),q=sx([x,v.y1]);svgEl('line',{x1:p[0],y1:p[1],x2:q[0],y2:q[1],stroke:'#FF3EC9','stroke-width':3,'stroke-dasharray':'5 5',filter:'url(#glow)'},svg)}if(state.snapVertex){let p=sx(state.snapVertex);svgEl('circle',{cx:p[0],cy:p[1],r:9,fill:'none',stroke:'#FF3EC9','stroke-width':2},svg)}}
 if(state.showVertices){let vs=vertices();vs.forEach((p,i)=>{let q=sx(p);svgEl('circle',{cx:q[0],cy:q[1],r:5,fill:MIN_COLOR,stroke:'#fff','stroke-width':1},svg);text(svg,`(${frac(p[0])}; ${frac(p[1])})`,q[0]+8,q[1]-8,10,'#fff','start')})}
 text(svg,'x',W-18,o[1]-10,12,'#E2E8F0','end');text(svg,'y',o[0]+10,18,12,'#E2E8F0','start');updateExplain(current);updateStepLabel(current);}
function text(svg,s,x,y,size,fill,anchor){let t=svgEl('text',{x,y,'font-size':size,fill,'text-anchor':anchor,'font-family':'Consolas, Segoe UI, sans-serif'},svg);t.textContent=s;return t}
function updateStepLabel(cur){$('stepLabel').textContent=cur?`Bước ${cur.no}/${state.steps.length}`:'Chưa giải'}
function updateExplain(cur){$('explain').textContent=explanation(cur);let box=$('vertexTable');if(state.showVertices){let vs=vertices();box.classList.remove('hidden');box.innerHTML='<b>ĐỈNH MIỀN NGHIỆM</b><table><tr><th>#</th><th>x</th><th>y</th></tr>'+vs.map((p,i)=>`<tr><td>${i+1}</td><td>${frac(p[0])}</td><td>${frac(p[1])}</td></tr>`).join('')+'</table>'}else box.classList.add('hidden')}
function panZoomSetup(){let svg=$('graph'),drag=null;svg.addEventListener('wheel',e=>{e.preventDefault();let r=svg.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,fx=mx/r.width,fy=my/r.height,px=state.view.x0+fx*(state.view.x1-state.view.x0),py=state.view.y1-fy*(state.view.y1-state.view.y0),factor=e.deltaY<0?.85:1/.85,nw=Math.max(.8,Math.min(55,(state.view.x1-state.view.x0)*factor)),nh=Math.max(.8,Math.min(55,(state.view.y1-state.view.y0)*factor));state.view.x0=px-fx*nw;state.view.x1=state.view.x0+nw;state.view.y1=py+fy*nh;state.view.y0=state.view.y1-nh;render();if(state.showObjective){setObjectiveCoeff()}} ,{passive:false});svg.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,v:{...state.view}};svg.setPointerCapture(e.pointerId);svg.style.cursor='grabbing'});svg.addEventListener('pointermove',e=>{let r=svg.getBoundingClientRect();let x=state.view.x0+(e.clientX-r.left)/r.width*(state.view.x1-state.view.x0),y=state.view.y1-(e.clientY-r.top)/r.height*(state.view.y1-state.view.y0);$('coord').textContent=`x = ${x.toFixed(2)}   y = ${y.toFixed(2)}`;if(!drag)return;let dx=(e.clientX-drag.x)/r.width*(drag.v.x1-drag.v.x0),dy=(e.clientY-drag.y)/r.height*(drag.v.y1-drag.v.y0);state.view.x0=drag.v.x0-dx;state.view.x1=drag.v.x1-dx;state.view.y0=drag.v.y0+dy;state.view.y1=drag.v.y1+dy;render()});svg.addEventListener('pointerup',e=>{drag=null;svg.style.cursor='grab'});svg.addEventListener('pointercancel',e=>{drag=null;svg.style.cursor='grab'})}
function bind(){['a','b','c'].forEach(k=>{let id='coef'+k.toUpperCase();$(id).addEventListener('focus',()=>state.activeField=k);$(id).addEventListener('keydown',e=>{if(e.key==='Enter')$('addBtn').click()})});$('addBtn').onclick=()=>addIneqText(`${$('coefA').value}x + ${$('coefB').value}y ${$('opSelect').value} ${$('coefC').value}`);$('solveBtn').onclick=solve;$('autoBtn').onclick=autoPlay;$('firstBtn').onclick=()=>{if(state.steps.length){state.stepIdx=0;render()}};$('prevBtn').onclick=()=>{if(state.steps.length&&state.stepIdx>0){state.stepIdx--;render()}};$('nextBtn').onclick=()=>{if(state.steps.length&&state.stepIdx<state.steps.length-1){state.stepIdx++;render()}};$('lastBtn').onclick=()=>{if(state.steps.length){state.stepIdx=state.steps.length-1;render()}};$('resetBtn').onclick=reset;$('verticesBtn').onclick=()=>{state.showVertices=!state.showVertices;$('verticesBtn').textContent=state.showVertices?'📐 Ẩn đỉnh':'📐 Hiện đỉnh';render()};$('objToggle').onclick=toggleObjective;$('objSlider').oninput=e=>{let [f,v]=snapF(parseFloat(e.target.value));state.objF=f;state.snapVertex=v;$('objSlider').value=f;updateObjLabel();render();if(v)setStatus(`🔒 Đường F đã khớp vào đỉnh (${frac(v[0])}; ${frac(v[1])}).`)};$('objA').addEventListener('change',setObjectiveCoeff);$('objB').addEventListener('change',setObjectiveCoeff);$('fitBtn').onclick=()=>{state.view={x0:XMIN,x1:XMAX,y0:YMIN,y1:YMAX};render()};let keys=[['7',''],['8',''],['9',''],['⌫','util'],['4',''],['5',''],['6',''],['C','util'],['1',''],['2',''],['3',''],['−',''],['0',''],['.',''],['/',''],['±','']];let kbox=$('keypad');keys.forEach(([s,c])=>{let b=document.createElement('button');b.textContent=s;if(c)b.className=c;b.onclick=()=>{let id='coef'+state.activeField.toUpperCase(),el=$(id);if(s==='⌫')el.value=el.value.slice(0,-1);else if(s==='C')el.value='';else if(s==='±')el.value=el.value.startsWith('-')?el.value.slice(1):'-'+el.value;else if(s==='−')el.value+='-';else el.value+=s;el.focus()};kbox.appendChild(b)})}
bind();panZoomSetup();loadDefault();render();
